// <auto-generated />
using System;
using GoodEatDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoodEatDatabase.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230111160043_InitialMigration1")]
    partial class InitialMigration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoodEatDatabase.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserRightID")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "antoine.pinloche@admin.com",
                            FirstName = "john",
                            LastName = "Doe",
                            Password = "password",
                            StartDate = new DateTime(2023, 1, 11, 17, 0, 43, 53, DateTimeKind.Local).AddTicks(5940),
                            UserRightID = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "antoine.pinloche@user.com",
                            FirstName = "john",
                            LastName = "Doe",
                            Password = "password",
                            StartDate = new DateTime(2023, 1, 11, 17, 0, 43, 53, DateTimeKind.Local).AddTicks(5999),
                            UserRightID = 2,
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
